[package]
name = "lurkff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
neptune = "8.1.0"
ff = "0.12.0"
generic-array = "0.14.4"
blstrs = "0.6.0"